name: Cypress Tests

on: 
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm startname: ManualTest

on: 
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: false
          parallel: true
          spec: './cypress/integration/examples/**'
      - name: Post Test
        if: failure()
        run: echo "Fail"
