name: Manual Tests
on: 
    workflow_dispatch:

jobs:
  cypress-run:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
          parallel: true
          spec: './cypress/integration/examples/**'
          
  send-failure-alerts:
    name: send failure alerts
    runs-on: ubuntu-latest
    needs: [cypress-run]
    if: failure()
    steps:
      - name: handle failure
        run: echo 'Failure 😑'
